apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: globe
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://github.com/klimatbyran/globe
  ref:
    branch: main
